MKPATH=../../mk/
include $(MKPATH)buildsys.mk

SUBDIRS = ambient tomenet
DATA = sound.cfg credits.txt \
	amb_bell_metal1.ogg       mco_scurry_dry.ogg        plm_glass_smashing.ogg \
	amb_bell_metal2.ogg       mco_shake_roll.ogg        plm_jar_ding.ogg \
	amb_bell_tibet1.ogg       mco_snarl_short.ogg \
	amb_bell_tibet2.ogg       mco_spray_long.ogg        plm_lock_case.ogg \
	amb_bell_tibet3.ogg       mco_squish_hit.ogg        plm_lock_distant.ogg \
	amb_deep.ogg              mco_squish_snap.ogg       plm_metal_clank.ogg \
	amb_door_doom.ogg         mco_strange_music.ogg     plm_metal_sharpen.ogg \
	amb_door_iron.ogg         mco_strange_thwoink.ogg   plm_open_case.ogg \
	amb_dungeon_echo.ogg      mco_thoing_backwards.ogg  plm_spell1.ogg \
	amb_dungeon_echowet.ogg   mco_thoing_deep.ogg       plm_spell2.ogg \
	amb_gong_chinese.ogg      mco_thud_crash.ogg        plm_spell3.ogg \
	amb_gong_low.ogg          mco_tube_hit.ogg          plm_use_staff.ogg \
	amb_gong_strike.ogg       plc_bell_warn.ogg         plm_wood_thud.ogg \
	amb_gong_undertone.ogg    plc_die_laugh.ogg         plm_zap_rod.ogg \
	amb_guitar_chord.ogg      plc_hit_anvil2.ogg        pls_bell_bowl.ogg \
	amb_melkor.ogg            plc_hit_anvil.ogg         pls_bell_chime_new.ogg \
	amb_morgoth.ogg           plc_hit_arrow.ogg         pls_bell_glass.ogg \
	amb_pulse_low.ogg         plc_hit_body.ogg          pls_bell_hibell_soft.ogg \
	amb_sauron.ogg            plc_hit_critical.ogg      pls_bell_mute.ogg \
	amb_senya.ogg             plc_hit_groan.ogg         pls_bell_sustain.ogg \
	amb_thunder_rain.ogg      plc_hit_grunt2.ogg        pls_breathe_in.ogg \
	amb_thunder_roll.ogg      plc_hit_grunt.ogg         pls_man_argoh.ogg \
	amb_xakaze.ogg            plc_hit_hay.ogg           pls_man_gulp_new.ogg \
	enter_pit.ogg             plc_miss_arrow2.ogg       pls_man_oooh.ogg \
	id_bad_aww.ogg            plc_miss_arrow.ogg        pls_man_scream2.ogg \
	id_bad_dang.ogg           plc_miss_swish.ogg        pls_man_sigh.ogg \
	id_bad_hmm.ogg            plm_aim_wand.ogg          pls_man_sniff.ogg \
	id_bad_hmph.ogg           plm_bang_ceramic.ogg      pls_man_sob.ogg \
	id_bad_ohh.ogg            plm_bang_dumpster.ogg     pls_man_spit.ogg \
	id_ego_whoa.ogg           plm_bang_metal.ogg        pls_man_ugh.ogg \
	id_ego_woohoo.ogg         plm_book_pageturn.ogg     pls_man_yell.ogg \
	id_ego_yeah2.ogg          plm_bottle_clinks.ogg     pls_tone_blurk.ogg \
	id_ego_yeah.ogg           plm_break_canister.ogg    pls_tone_clave6.ogg \
	id_ego_yes.ogg            plm_break_glass2.ogg      pls_tone_clavelo8.ogg \
	id_good_hey2.ogg          plm_break_glass.ogg       pls_tone_conk.ogg \
	id_good_hey.ogg           plm_break_plates.ogg      pls_tone_elec.ogg \
	id_good_hmm.ogg           plm_break_shatter.ogg     pls_tone_goblet.ogg \
	id_good_huh.ogg           plm_break_smash.ogg       pls_tone_guiro.ogg \
	id_good_ooh.ogg           plm_break_wood.ogg        pls_tone_headstock.ogg \
	id_good_ooo.ogg           plm_cabinet_open.ogg      pls_tone_scrape.ogg \
	id_good_wow.ogg           plm_cabinet_shut.ogg      pls_tone_stick.ogg \
	mco_attack_breath.ogg     plm_chain_light.ogg       sto_bell_desk.ogg \
	mco_attack_spray.ogg      plm_chest_latch.ogg       sto_bell_dingaling.ogg \
	mco_bite_chew.ogg         plm_chest_unlatch.ogg     sto_bell_ding.ogg \
	mco_bite_chomp.ogg        plm_chimes_jangle.ogg     sto_bell_jingles.ogg \
	mco_bite_dainty.ogg       plm_click_dry.ogg         sto_bell_register1.ogg \
	mco_bite_gnash.ogg        plm_click_switch2.ogg     sto_bell_register2.ogg \
	mco_bite_hard.ogg         plm_click_switch3.ogg     sto_bell_ringing.ogg \
	mco_bite_long.ogg         plm_click_switch.ogg      sto_bell_shop.ogg \
	mco_bite_munch.ogg        plm_click_wood.ogg        sto_coins_countertop.ogg \
	mco_bite_regular.ogg      plm_close_hatch.ogg       sto_man_haha.ogg \
	mco_bite_short.ogg        plm_coins_dump.ogg        sto_man_hey.ogg \
	mco_bite_small.ogg        plm_coins_light.ogg       sto_man_whoohaha.ogg \
	mco_bite_soft.ogg         plm_coins_pour.ogg        sum_angel_song.ogg \
	mco_card_shuffle.ogg      plm_coins_shake.ogg       sum_bell_crystal.ogg \
	mco_castanet_trill.ogg    plm_cork_pop.ogg          sum_bell_hand.ogg \
	mco_ceramic_trill.ogg     plm_cork_squeak.ogg       sum_bell_tone.ogg \
	mco_click_vibra.ogg       plm_door_bolt.ogg         sum_chime_jangle.ogg \
	mco_creature_choking.ogg  plm_door_creak.ogg        sum_ghost_moan.ogg \
	mco_creature_groan.ogg    plm_door_creakshut.ogg    sum_ghost_oooo.ogg \
	mco_creature_yelp.ogg     plm_door_dungeon.ogg      sum_ghost_wail.ogg \
	mco_cuica_rubbing.ogg     plm_door_echolock.ogg     sum_gong_temple.ogg \
	mco_dino_low.ogg          plm_door_entrance.ogg     sum_laugh_evil2.ogg \
	mco_dino_slur.ogg         plm_door_knob.ogg         sum_lion_growl.ogg  \
	mco_dino_talk.ogg         plm_door_latch.ogg        sum_piano_scrape.ogg \
	mco_dino_yawn.ogg         plm_door_opening.ogg      wild_deepwater.ogg \
	mco_dub_wobble.ogg        plm_door_open.ogg         wild_desert.ogg \
	mco_frog_trill.ogg        plm_door_rusty.ogg        wild_glacier.ogg \
	mco_hit_whip.ogg          plm_door_shut.ogg         wild_grass.ogg \
	mco_howl_croak.ogg        plm_door_slam.ogg         wild_hill.ogg \
	mco_howl_deep.ogg         plm_door_squeaky.ogg      wild_hill2.ogg \
	mco_howl_distressed.ogg   plm_door_wooden.ogg       wild_river.ogg \
	mco_howl_high.ogg         plm_drop_boot.ogg         wild_shore.ogg \
	mco_howl_long.ogg         plm_eat_bite.ogg          wild_swamp.ogg \
	mco_liquid_squirt.ogg     plm_floor_creak2.ogg      wild_volcano.ogg \
	mco_man_mumble.ogg        plm_floor_creak.ogg       wild_waste.ogg \
	mco_mouse_squeaks.ogg     plm_glass_breaking.ogg    wild_wolf.ogg \
	mco_rubber_thud.ogg       plm_glass_break.ogg \
	amb_bell_metal1.mp3       mco_scurry_dry.mp3        plm_glass_smashing.mp3 \
	amb_bell_metal2.mp3       mco_shake_roll.mp3        plm_jar_ding.mp3 \
	amb_bell_tibet1.mp3       mco_snarl_short.mp3 \
	amb_bell_tibet2.mp3       mco_spray_long.mp3        plm_lock_case.mp3 \
	amb_bell_tibet3.mp3       mco_squish_hit.mp3        plm_lock_distant.mp3 \
	amb_deep.mp3              mco_squish_snap.mp3       plm_metal_clank.mp3 \
	amb_door_doom.mp3         mco_strange_music.mp3     plm_metal_sharpen.mp3 \
	amb_door_iron.mp3         mco_strange_thwoink.mp3   plm_open_case.mp3 \
	amb_dungeon_echo.mp3      mco_thoing_backwards.mp3  plm_spell1.mp3 \
	amb_dungeon_echowet.mp3   mco_thoing_deep.mp3       plm_spell2.mp3 \
	amb_gong_chinese.mp3      mco_thud_crash.mp3        plm_spell3.mp3 \
	amb_gong_low.mp3          mco_tube_hit.mp3          plm_use_staff.mp3 \
	amb_gong_strike.mp3       plc_bell_warn.mp3         plm_wood_thud.mp3 \
	amb_gong_undertone.mp3    plc_die_laugh.mp3         plm_zap_rod.mp3 \
	amb_guitar_chord.mp3      plc_hit_anvil2.mp3        pls_bell_bowl.mp3 \
	amb_melkor.mp3            plc_hit_anvil.mp3         pls_bell_chime_new.mp3 \
	amb_morgoth.mp3           plc_hit_arrow.mp3         pls_bell_glass.mp3 \
	amb_pulse_low.mp3         plc_hit_body.mp3          pls_bell_hibell_soft.mp3 \
	amb_sauron.mp3            plc_hit_critical.mp3      pls_bell_mute.mp3 \
	amb_senya.mp3             plc_hit_groan.mp3         pls_bell_sustain.mp3 \
	amb_thunder_rain.mp3      plc_hit_grunt2.mp3        pls_breathe_in.mp3 \
	amb_thunder_roll.mp3      plc_hit_grunt.mp3         pls_man_argoh.mp3 \
	amb_xakaze.mp3            plc_hit_hay.mp3           pls_man_gulp_new.mp3 \
	enter_pit.mp3             plc_miss_arrow2.mp3       pls_man_oooh.mp3 \
	id_bad_aww.mp3            plc_miss_arrow.mp3        pls_man_scream2.mp3 \
	id_bad_dang.mp3           plc_miss_swish.mp3        pls_man_sigh.mp3 \
	id_bad_hmm.mp3            plm_aim_wand.mp3          pls_man_sniff.mp3 \
	id_bad_hmph.mp3           plm_bang_ceramic.mp3      pls_man_sob.mp3 \
	id_bad_ohh.mp3            plm_bang_dumpster.mp3     pls_man_spit.mp3 \
	id_ego_whoa.mp3           plm_bang_metal.mp3        pls_man_ugh.mp3 \
	id_ego_woohoo.mp3         plm_book_pageturn.mp3     pls_man_yell.mp3 \
	id_ego_yeah2.mp3          plm_bottle_clinks.mp3     pls_tone_blurk.mp3 \
	id_ego_yeah.mp3           plm_break_canister.mp3    pls_tone_clave6.mp3 \
	id_ego_yes.mp3            plm_break_glass2.mp3      pls_tone_clavelo8.mp3 \
	id_good_hey2.mp3          plm_break_glass.mp3       pls_tone_conk.mp3 \
	id_good_hey.mp3           plm_break_plates.mp3      pls_tone_elec.mp3 \
	id_good_hmm.mp3           plm_break_shatter.mp3     pls_tone_goblet.mp3 \
	id_good_huh.mp3           plm_break_smash.mp3       pls_tone_guiro.mp3 \
	id_good_ooh.mp3           plm_break_wood.mp3        pls_tone_headstock.mp3 \
	id_good_ooo.mp3           plm_cabinet_open.mp3      pls_tone_scrape.mp3 \
	id_good_wow.mp3           plm_cabinet_shut.mp3      pls_tone_stick.mp3 \
	mco_attack_breath.mp3     plm_chain_light.mp3       sto_bell_desk.mp3 \
	mco_attack_spray.mp3      plm_chest_latch.mp3       sto_bell_dingaling.mp3 \
	mco_bite_chew.mp3         plm_chest_unlatch.mp3     sto_bell_ding.mp3 \
	mco_bite_chomp.mp3        plm_chimes_jangle.mp3     sto_bell_jingles.mp3 \
	mco_bite_dainty.mp3       plm_click_dry.mp3         sto_bell_register1.mp3 \
	mco_bite_gnash.mp3        plm_click_switch2.mp3     sto_bell_register2.mp3 \
	mco_bite_hard.mp3         plm_click_switch3.mp3     sto_bell_ringing.mp3 \
	mco_bite_long.mp3         plm_click_switch.mp3      sto_bell_shop.mp3 \
	mco_bite_munch.mp3        plm_click_wood.mp3        sto_coins_countertop.mp3 \
	mco_bite_regular.mp3      plm_close_hatch.mp3       sto_man_haha.mp3 \
	mco_bite_short.mp3        plm_coins_dump.mp3        sto_man_hey.mp3 \
	mco_bite_small.mp3        plm_coins_light.mp3       sto_man_whoohaha.mp3 \
	mco_bite_soft.mp3         plm_coins_pour.mp3        sum_angel_song.mp3 \
	mco_card_shuffle.mp3      plm_coins_shake.mp3       sum_bell_crystal.mp3 \
	mco_castanet_trill.mp3    plm_cork_pop.mp3          sum_bell_hand.mp3 \
	mco_ceramic_trill.mp3     plm_cork_squeak.mp3       sum_bell_tone.mp3 \
	mco_click_vibra.mp3       plm_door_bolt.mp3         sum_chime_jangle.mp3 \
	mco_creature_choking.mp3  plm_door_creak.mp3        sum_ghost_moan.mp3 \
	mco_creature_groan.mp3    plm_door_creakshut.mp3    sum_ghost_oooo.mp3 \
	mco_creature_yelp.mp3     plm_door_dungeon.mp3      sum_ghost_wail.mp3 \
	mco_cuica_rubbing.mp3     plm_door_echolock.mp3     sum_gong_temple.mp3 \
	mco_dino_low.mp3          plm_door_entrance.mp3     sum_laugh_evil2.mp3 \
	mco_dino_slur.mp3         plm_door_knob.mp3         sum_lion_growl.mp3  \
	mco_dino_talk.mp3         plm_door_latch.mp3        sum_piano_scrape.mp3 \
	mco_dino_yawn.mp3         plm_door_opening.mp3      wild_deepwater.mp3 \
	mco_dub_wobble.mp3        plm_door_open.mp3         wild_desert.mp3 \
	mco_frog_trill.mp3        plm_door_rusty.mp3        wild_glacier.mp3 \
	mco_hit_whip.mp3          plm_door_shut.mp3         wild_grass.mp3 \
	mco_howl_croak.mp3        plm_door_slam.mp3         wild_hill.mp3 \
	mco_howl_deep.mp3         plm_door_squeaky.mp3      wild_hill2.mp3 \
	mco_howl_distressed.mp3   plm_door_wooden.mp3       wild_river.mp3 \
	mco_howl_high.mp3         plm_drop_boot.mp3         wild_shore.mp3 \
	mco_howl_long.mp3         plm_eat_bite.mp3          wild_swamp.mp3 \
	mco_liquid_squirt.mp3     plm_floor_creak2.mp3      wild_volcano.mp3 \
	mco_man_mumble.mp3        plm_floor_creak.mp3       wild_waste.mp3 \
	mco_mouse_squeaks.mp3     plm_glass_breaking.mp3    wild_wolf.mp3 \
	mco_rubber_thud.mp3       plm_glass_break.mp3 \
    blind.ogg                 blind1.ogg                blind2.ogg \
    confused.ogg              hypnotize.ogg             afraid.ogg \
    cut.ogg                   hallucinate.ogg           paralyzed.ogg \
    poison.ogg                slow.ogg                  stun1.ogg \
    stun2.ogg                 stun3.ogg                 immune1.ogg \
    immune2.ogg               immune3.ogg               immune4.ogg \
    immune5.ogg               immune6.ogg               immune7.ogg \
    immune8.ogg               resist_a_lot1.ogg         resist_a_lot2.ogg \
    resist_a_lot3.ogg         resist_a_lot4.ogg         resist_a_lot5.ogg \
    resist_a_lot6.ogg         resist_a_lot7.ogg         resist.ogg \
    spell_fail.ogg            mon_devour.ogg            mon_swallow.ogg \
    imp_giggles.ogg           werewolf_howl.ogg         terrain_slip.ogg \
    dig1.ogg                  dig2.ogg                  dig3.ogg \
    dig4.ogg                  dig5.ogg                  dig6.ogg \
    chop1.ogg                 chop2.ogg                 chop3.ogg \
    chop4.ogg                 chop5.ogg                 chop6.ogg \
    chop_tree_fall.ogg        sentry.ogg                door_broken.ogg \
    silent.ogg                silent0.ogg               quiver.ogg \
    silent100.ogg             silent101.ogg \
    item_pickup.ogg           gold_1.ogg                gold_2.ogg \
    backpack_1.ogg            backpack_2.ogg            backpack_3.ogg \
    backpack_4.ogg            backpack_5.ogg            backpack_6.ogg \
    backpack_7.ogg            backpack_8.ogg            backpack_9.ogg \
    backpack_10.ogg           backpack_11.ogg           backpack_12.ogg \
    backpack_13.ogg           backpack_14.ogg           backpack_15.ogg \
    backpack_16.ogg           backpack_17.ogg           backpack_18.ogg \
    item_medium_armor.ogg     item_pickup_1.ogg         wilhelm-scream.ogg \
    item_light_lantern_1.ogg  item_light_lantern_2.ogg  item_light_lamp_1.ogg \
    item_light_lamp_2.ogg     item_light_phial_1.ogg    item_light_phial_2.ogg \
    item_light_palantir_1.ogg item_light_palantir_2.ogg kill_unique_yaga.ogg \
    blind.mp3                 blind1.mp3                blind2.mp3 \
    confused.mp3              hypnotize.mp3             afraid.mp3 \
    cut.mp3                   hallucinate.mp3           paralyzed.mp3 \
    poison.mp3                slow.mp3                  stun1.mp3 \
    stun2.mp3                 stun3.mp3                 immune1.mp3 \
    immune2.mp3               immune3.mp3               immune4.mp3 \
    immune5.mp3               immune6.mp3               immune7.mp3 \
    immune8.mp3               resist_a_lot1.mp3         resist_a_lot2.mp3 \
    resist_a_lot3.mp3         resist_a_lot4.mp3         resist_a_lot5.mp3 \
    resist_a_lot6.mp3         resist_a_lot7.mp3         resist.mp3 \
    spell_fail.mp3            mon_devour.mp3            mon_swallow.mp3 \
    imp_giggles.mp3           werewolf_howl.mp3         terrain_slip.mp3 \
    dig1.mp3                  dig2.mp3                  dig3.mp3 \
    dig4.mp3                  dig5.mp3                  dig6.mp3 \
    chop1.mp3                 chop2.mp3                 chop3.mp3 \
    chop4.mp3                 chop5.mp3                 chop6.mp3 \
    chop_tree_fall.mp3        sentry.mp3                door_broken.mp3 \
    silent.mp3                silent0.mp3               quiver.mp3 \
    silent100.mp3             silent101.mp3 \
    item_pickup.mp3           gold_1.mp3                gold_2.mp3 \
    backpack_1.mp3            backpack_2.mp3            backpack_3.mp3 \
    backpack_4.mp3            backpack_5.mp3            backpack_6.mp3 \
    backpack_7.mp3            backpack_8.mp3            backpack_9.mp3 \
    backpack_10.mp3           backpack_11.mp3           backpack_12.mp3 \
    backpack_13.mp3           backpack_14.mp3           backpack_15.mp3 \
    backpack_16.mp3           backpack_17.mp3           backpack_18.mp3 \
    item_medium_armor.mp3     item_pickup_1.mp3         wilhelm-scream.mp3 \
    item_light_lantern_1.mp3  item_light_lantern_2.mp3  item_light_lamp_1.mp3 \
    item_light_lamp_2.mp3     item_light_phial_1.mp3    item_light_phial_2.mp3 \
    item_light_palantir_1.mp3 item_light_palantir_2.mp3 kill_unique_yaga.mp3 \
    ambient_birds.ogg ambient_birds_1.ogg ambient_birds_2.ogg ambient_crow.ogg ambient_forest_birds.ogg ambient_fox.ogg \
    ambient_birds.mp3 ambient_birds_1.mp3 ambient_birds_2.mp3 ambient_crow.mp3 ambient_forest_birds.mp3 ambient_fox.mp3 \
    ambient_wind_1.ogg ambient_wind_2.ogg ambient_wind_3.ogg ambient_wind_night_1.ogg ambient_wind_night.ogg ambient_wings.ogg \
    ambient_wind_1.mp3 ambient_wind_2.mp3 ambient_wind_3.mp3 ambient_wind_night_1.mp3 ambient_wind_night.mp3 ambient_wings.mp3 \
    arc.ogg beam.ogg blast.ogg burn_1.ogg burn_2.ogg danger_9.ogg \
    arc.mp3 beam.mp3 blast.mp3 burn_1.mp3 burn_2.mp3 danger_9.mp3 \
    defeat_unique_shtukensia.ogg detect.ogg glyph.ogg kill_king.ogg kill_slime_1.ogg kill_slime_2.ogg \
    defeat_unique_shtukensia.mp3 detect.mp3 glyph.mp3 kill_king.mp3 kill_slime_1.mp3 kill_slime_2.mp3 \
    kill_slime_3.ogg kill_slime_4.ogg kill_slime_5.ogg kill_slime_6.ogg kill_slime_7.ogg kill_slime_8.ogg \
    kill_slime_3.mp3 kill_slime_4.mp3 kill_slime_5.mp3 kill_slime_6.mp3 kill_slime_7.mp3 kill_slime_8.mp3 \
    kill_slime.ogg kill_stinger.ogg kill_unique_shelob.ogg kill_unique_witch_king.ogg lash.ogg melee_blows.ogg \
    kill_slime.mp3 kill_stinger.mp3 kill_unique_shelob.mp3 kill_unique_witch_king.mp3 lash.mp3 melee_blows.mp3 \
    message.ogg paths_of_the_dead.ogg \
    message.mp3 paths_of_the_dead.mp3 \
    project.ogg spot.ogg star.ogg strike.ogg touch.ogg enter_barrow.ogg \
    project.mp3 spot.mp3 star.mp3 strike.mp3 touch.mp3 enter_barrow.mp3 \
    enter_ruins.ogg explosion_1.ogg kill_koschei.ogg kill_mushroom_10.ogg kill_mushroom_11.ogg kill_mushroom_1.ogg \
    enter_ruins.mp3 explosion_1.mp3 kill_koschei.mp3 kill_mushroom_10.mp3 kill_mushroom_11.mp3 kill_mushroom_1.mp3 \
    kill_mushroom_2.ogg kill_mushroom_3.ogg kill_mushroom_4.ogg kill_mushroom_5.ogg kill_mushroom_6.ogg kill_mushroom_7.ogg \
    kill_mushroom_2.mp3 kill_mushroom_3.mp3 kill_mushroom_4.mp3 kill_mushroom_5.mp3 kill_mushroom_6.mp3 kill_mushroom_7.mp3 \
    kill_mushroom_8.ogg kill_mushroom_9.ogg kill_unique_angel.ogg manor.ogg orc_caves.ogg vulture.ogg \
    kill_mushroom_8.mp3 kill_mushroom_9.mp3 kill_unique_angel.mp3 manor.mp3 orc_caves.mp3 vulture.mp3

PACKAGE = sounds
