MKPATH=../../mk/
include $(MKPATH)buildsys.mk

CONFIG = activation.txt admin_stuff.txt artifact.txt blow_effects.txt \
 blow_methods.txt body.txt brand.txt chest_trap.txt class.txt constants.txt \
 curse.txt dragon_breed.txt dungeon_profile.txt dungeon.txt ego_item.txt flavor.txt \
 hints.txt history.txt level_golds.txt monster_base.txt monster_spell.txt monster.txt \
 names.txt object_base.txt object_power.txt object_property.txt object.txt p_race.txt \
 pain.txt pit.txt player_property.txt player_timed.txt projection.txt quest.txt \
 realm.txt room_template.txt slay.txt socials.txt store.txt summon.txt \
 terrain.txt town_-1_-1.txt town_-1_-2.txt town_-1_-3.txt town_-1_-4.txt town_-1_0.txt \
 town_-1_2.txt town_-1_3.txt town_-2_-1.txt town_-2_0.txt town_-2_1.txt town_-2_2.txt \
 town_-2_3.txt town_-3_0.txt town_-5_0.txt town_0_-1.txt town_0_-2.txt town_0_-3.txt \
 town_0_-4.txt town_0_-5.txt town_0_0.txt town_0_1.txt town_0_2.txt town_0_3.txt \
 town_0_4.txt town_0_5.txt town_1_-1.txt town_1_-2.txt town_1_-3.txt town_1_-4.txt \
 town_1_-5.txt town_1_-11.txt town_1_0.txt town_1_1.txt town_1_2.txt town_1_3.txt \
 town_2_0.txt town_2_1.txt town_2_2.txt town_2_3.txt town_bree.txt town_empty.txt \
 town_feat.txt town_gondolin.txt town_lothlorien.txt town_minas_anor.txt town_test.txt \
 town_umbar.txt town_underground.txt town.txt trap.txt vault.txt visuals.txt \
 wild_feat.txt wild_info.txt
PACKAGE = gamedata
