MKPATH=../../mk/
include $(MKPATH)buildsys.mk

CONFIG = \
       font-gcu.prf font-sdl.prf font-sdl.prf.default font-win.prf font-win.prf.default \
       font.prf font-tng.prf \
       message.prf pref.prf user.prf sound.prf \
       class.prf presets.prf race.prf

PACKAGE = customize
