MKPATH=../../mk/
include $(MKPATH)buildsys.mk

DATA = 3x5TG.fon 5x8TG.FON 5x8x.fon 6x9TG.FON 6x10TG.FON 6x10x.fon \
	6x12TG.FON 6x12x.fon 6x13TG.FON 6x13x.fon 6x13xb.fon 7x13TG.FON 7x13x.fon \
	7x13xb.fon 8x8x.fon 8x8xb.fon 8x12x.fon 8x12xb.fon 8x13TG.FON 8x13x.fon \
	8x16tx.fon 8x16x.fon 9x15TG.FON 9x15x.fon 9x15xb.fon 10x14TG.FON 10x14x.fon \
	10x14xb.fon 10x16TG.FON 10x17TG.FON 10x20TG.FON 10x20x.fon 12x17TG.FON 12x18TG.FON \
	12x18x.fon 12x24TG.FON 12x24x.fon 14x20TG.FON 16x16TG.FON 16x16x.fon 16x16xw.fon \
	16x22TG.FON 16x24TG.FON 16x24tx.fon 16x24x.fon 17x25TG.FON 19x29TG.FON 21x31tg.fon \
	21x31tgs.fon 21x31x.fon 24x36tg.fon \
	AnonymousPro-Bold.ttf Cousine-Bold.ttf IBMPlexMono-Bold.ttf JetBrainsMono-SemiBold.ttf \
	RobotoMono-Bold.ttf SourceCodePro-SemiBold.ttf Tangaria-tg.ttf Tangaria-tgs.ttf \
	UbuntuMono-Bold-tg.ttf UbuntuMono-Regular-tg.ttf
PACKAGE = fonts
